{% set name = "litex" %}
{% set version = "2024.12" %}
{% set sha256 = "afc435ccc86ef9dda79217334c9e5ba8c9991b2101e59d4420a28e188343cc1d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - litex_term = litex.tools.litex_term:main
    - litex_server = litex.tools.litex_server:main
    - litex_cli = litex.tools.litex_client:main
    - litex_soc_gen = litex.tools.litex_soc_gen:main
    - litex_periph_gen = litex.tools.litex_periph_gen:main
    - litex_sim = litex.tools.litex_sim:main
    - litex_bare_metal_demo = litex.soc.software.demo.demo:main
    - litex_json2dts_linux = litex.tools.litex_json2dts_linux:main
    - litex_json2dts_zephyr = litex.tools.litex_json2dts_zephyr:main
    - litex_json2renode = litex.tools.litex_json2renode:main
    - litex_read_verilog = litex.tools.litex_read_verilog:main
    - litex_contributors = litex.tools.litex_contributors:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - migen
    - pyserial
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - litex
  commands:
    - litex_cli --help

about:
  home: https://github.com/enjoy-digital/litex
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The LiteX framework provides a convenient and efficient infrastructure to create FPGA Cores/SoCs, to explore various digital design architectures and create full FPGA based systems
  description: |
    The LiteX framework provides a convenient and efficient infrastructure to create FPGA Cores/SoCs, to explore various digital design architectures and create full FPGA based systems
  dev_url: https://github.com/enjoy-digital/litex

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
