{% set name = "litex" %}
{% set version = "2022.12" %}
{% set sha256 = "4b0b7d6d855f644ac8b2a4f359ff5af00bfff998bae8d0475114c6f0e5757f45" %}

package:
   name: {{ name|lower }}
   version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-patch-version.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  entry_points:
    - litex_term = litex.tools.litex_term:main
    - litex_server = litex.tools.litex_server:main
    - litex_cli = litex.tools.litex_client:main
    - litex_soc_gen = litex.tools.litex_soc_gen:main
    - litex_periph_gen = litex.tools.litex_periph_gen:main
    - litex_sim = litex.tools.litex_sim:main
    - litex_bare_metal_demo = litex.soc.software.demo.demo:main
    - litex_json2dts_linux = litex.tools.litex_json2dts_linux:main
    - litex_json2dts_zephyr = litex.tools.litex_json2dts_zephyr:main
    - litex_json2renode = litex.tools.litex_json2renode:main
    - litex_read_verilog = litex.tools.litex_read_verilog:main
    - litex_contributors = litex.tools.litex_contributors:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - migen
    - pyserial
    - requests

test:
  imports:
    - litex
  commands:
    - litex_cli --help

about:
  home: https://github.com/enjoy-digital/litex
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The LiteX framework provides a convenient and efficient infrastructure to create FPGA Cores/SoCs, to explore various digital design architectures and create full FPGA based systems
  description: |
    The LiteX framework provides a convenient and efficient infrastructure to create FPGA Cores/SoCs, to explore various digital design architectures and create full FPGA based systems
  dev_url: https://github.com/enjoy-digital/litex

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
